import sys, os

agenversion = "0.1b"

class txtcolor:
    CEND = '\33[0m'
    CRED = '\33[31m'
    CGREEN = '\33[32m'
    CBLUE = '\33[34m'
    CGREY = '\33[90m'

def color_input(txt):
    return input(txtcolor.CBLUE + txt + txtcolor.CGREEN + txtcolor.CEND)

def print_split():
    return print(txtcolor.CGREY + "\n-------------------------------------------------------------------------------" + txtcolor.CEND)

def error(txt):
    return print(txtcolor.CRED + "[ERROR] " + txt + txtcolor.CEND)

print("\nWhat do you want to do ? :")
print(" 1 - Make a new virtualhost")
print_split()
action = color_input("Select the appropriate number (Enter 'c' to cancel and exit) : [1] ")

if(action.upper() == "C"):
    print("\n*- Leaving A2Gen version {} -*".format(agenversion))
    sys.exit(1)

if(action == "1" or action == ""):

    """Vhost Port"""
    print_split()
    port = color_input("In which port apache should broadcast the VHost ? : [80] ")
    if not port:
        port = "80"

    """Server Name"""
    print_split()
    servername = ""
    while not servername:
        servername = color_input("[REQUIRED] Enter the server name of the VHost (eg: john.domain.com) : ")

    """Server Admin"""
    print_split()
    serveradmin = color_input("Enter the email of the VirtualHost administrator (eg: john@doe.com) : ")

    """Type of site"""
    print_split()
    print("Precise if the VHost is a HTTP proxy or just a directory broadcasting : ")
    print("1 : HTTP Proxy")
    print("2 : File serving")
    typesite = color_input("Select the appropriate number : (1-2) [2] ")
    if not typesite:
        typesite = "2"

    """FOR FILE SERVING"""
    if typesite == "2":

        """DOC ROOT"""
        print_split()
        docroot = ""
        while not docroot:
            docroot = color_input("Directory of the documents (eg: /var/www/shop) : ")

    """For HTTP Proxy"""
    if typesite == "1":

        """ProxyPass"""
        print_split()
        proxypassurl = color_input("URL Where you want to deserve the App's : [/] ")
        proxypassurl = "/"

        print(proxypassurl)
        """ProxyPass ADDR"""
        print_split()
        proxypassaddr =  ""
        while not proxypassaddr:
            proxypassaddr = color_input("[REQUIRED] Address with port of the App's you want Proxy (eg: http://127.0.0.1:3000/) : ")

        """Preserve Host ?"""
        print_split()
        proxypreservhost = color_input("Preserve host's headers ? : (Y-N) [N]")

        """Requests ?"""
        print_split()
        proxyrequests = color_input("Direct mandatory ? (ProxyRequests) : (Y-N) [N] ")

    """Output type"""
    print_split()
    basic_export_file_addr = servername.replace(".", "-")
    print("How/Where export the VHost ?")
    print("1 : Save it in /etc/apache2/sites-avaliables/{}.conf".format(basic_export_file_addr))
    print("2 : Save it in /etc/apache2/sites-avaliables/ with a custom name")
    print("3 : Save it in a custom directory")
    print("4 : Print it in the terminal")
    print("5 : Clear the terminal and print inside")
    outtype = color_input("Select the appropriate number : (1-5) [1] ")
    if not outtype:
        outtype = "1"

    """GENERATING CONF FILE"""
    conf_file = "<VirtualHost *:{0}>\n\tServerName {1}".format(port, servername)
    conf_file = conf_file + "\n\t# - Generated by A2Gen v{} -".format(agenversion)
    if serveradmin:
        conf_file = conf_file + "\n\tServerAdmin {}".format(serveradmin)
    if typesite == "2":
        conf_file = conf_file + "\n\tDocumentRoot {}".format(docroot)
    if typesite == "1":
        conf_file = conf_file + "\n\tProxyPass {} {}".format(proxypassurl, proxypassaddr)
        if proxypreservhost.upper == "Y":
            conf_file = conf_file + "\n\tProxyPreserveHost On"
        elif proxypreservhost.upper() == "N":
            conf_file = conf_file + "\n\tProxyPreserveHost Off"
        if proxyrequests.upper() == "Y":
            conf_file = conf_file + "\n\tProxyRequests On"
        elif proxyrequests.upper() == "Y":
            conf_file = conf_file + "\n\tProxyRequests Off"
    conf_file = conf_file + "\n</VirtualHost>"

    """Export with name of servername"""
    if outtype ==  "1":
        try:
            vhost = open("/etc/apache2/sites-available/{}.conf".format(servername.replace(".", "-")), "w+")
            vhost.write(conf_file)
        except PermissionError:
            color_error("Can't write the file in /etc/apache2/sites-available/{}. ".format(basic_export_file_addr))
            print("The VHost will be printed in your terminal.")
            print("\n{}\n\n".format(conf_file))

    """export with a custom name"""
    if outtype == "2":
        vhost_name = ""
        while not vhost_name:
            vhost_name = color_input("How to call the VHost's configuration file ? (eg: mainsite.conf) ")

        """Verifing if .conf extension ?"""
        if not vhost_name.endswith(".conf"):
            vhost_name_endwith = color_input("The VHost name \"{}\" don't have .conf extension, add it ? (Y/N) [Y] ".format(vhost_name))

            if vhost_name_endwith.upper() == "Y" or vhost_name_endwith == "":
                vhost_name = vhost_name + ".conf"

        try:
            vhost = open("/etc/apache2/sites-available/" + vhost_name, "w+")
            vhost.write(conf_file)
        except PermissionError:
            color_error("Can't write the file in /etc/apache2/sites-available/{}. ".format(vhost_name))
            print("The VHost will be printed in your terminal.")
            print("\n{}\n\n".format(conf_file))

        """export in custom dir"""
    elif outtype == "3":
        vhost_export_addr = ""
        while not vhost_export_addr:
            vhost_export_addr = color_input("Where save the VHost ? (enter the real path, eg: /home/john/john.com.conf) : ")

        """Verifing if .conf extension ?"""
        if not vhost_export_addr.endswith(".conf"):
            vhost_path_endwith = color_input("The VHost \"{}\" don't have .conf extension, add it ? (Y/N) [Y] ".format(vhost_export_addr))

            if vhost_path_endwith.upper() == "Y" or vhost_path_endwith == "":
                vhost_export_addr = vhost_export_addr + ".conf"
        try:
            vhost = open(vhost_export_addr, "w+")
            vhost.write(conf_file)

        except PermissionError:
            color_error("Can't write the file in /etc/apache2/sites-available/{}. ".format(vhost_name))
            print("The VHost will be printed in your terminal.")
            print("\n{}\n\n".format(conf_file))
        except FileNotFoundError:
            color_error("Can't found the path.")

    """Just print"""
    elif outtype == "4":
        print("\n\n" + conf_file + "\n\n")

    """Clear & print"""
    elif outtype == "5":
        os.system('cls' if os.name == 'nt' else 'clear')
        print("\n\n" + conf_file + "\n\n")

    print("~~~ Goodbye ~~~")
    print("Leaving A2Gen version {} - https://github.com/outout14/a2gen".format(agenversion))
print(conf_file)

